### ISSUE TITLE
Unable to resolve NULL driver for [LaravelFCM\FCMManager]

### ISSUE THREAD

**Issue by MJegorovas** [brozot/Laravel-FCM#167]
I set up the project as in doc (require, publish, package configuration, etc.). Try a notification example and got this error:
```
Unable to resolve NULL driver for [LaravelFCM\FCMManager]. {"exception":"[object] (InvalidArgumentException(code: 0): Unable to resolve NULL driver for [LaravelFCM\\FCMManager]. at vendor\\laravel\\framework\\src\\Illuminate\\Support\\Manager.php:81)
[stacktrace]
#0 vendor\\brozot\\laravel-fcm\\src\\FCMServiceProvider.php(32): Illuminate\\Support\\Manager->driver()
#1 vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(799): LaravelFCM\\FCMServiceProvider->LaravelFCM\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#2 vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(681): Illuminate\\Container\\Container->build(Object(Closure))
#3 vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(629): Illuminate\\Container\\Container->resolve('fcm.client', Array)
#4 vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(768): Illuminate\\Container\\Container->make('fcm.client', Array)
#5 vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(1245): Illuminate\\Foundation\\Application->make('fcm.client')
#6 vendor\\brozot\\laravel-fcm\\src\\FCMServiceProvider.php(43): Illuminate\\Container\\Container->offsetGet('fcm.client')
#7 vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(799): LaravelFCM\\FCMServiceProvider->LaravelFCM\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#8 vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(681): Illuminate\\Container\\Container->build(Object(Closure))
#9 vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(629): Illuminate\\Container\\Container->resolve('fcm.sender', Array)
#10 vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(768): Illuminate\\Container\\Container->make('fcm.sender', Array)
#11 vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(1245): Illuminate\\Foundation\\Application->make('fcm.sender')
#12 vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(182): Illuminate\\Container\\Container->offsetGet('fcm.sender')
#13 vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(150): Illuminate\\Support\\Facades\\Facade::resolveFacadeInstance('fcm.sender')
#14 vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(239): Illuminate\\Support\\Facades\\Facade::getFacadeRoot()
#15 app\\Http\\Controllers\\NotificationController.php(25): Illuminate\\Support\\Facades\\Facade::__callStatic('sendTo', Array)
#16 [internal function]: App\\Http\\Controllers\\NotificationController->sendNotification()
```
In `new FCMManager($app)`(FCMServiceProvider.php:32) I get:
```
LaravelFCM\FCMManager {#305 ▼
  #container: Illuminate\Foundation\Application {#2 ▶}
  #app: Illuminate\Foundation\Application {#2 ▶}
  #config: Illuminate\Config\Repository {#42 ▶}
  #customCreators: []
  #drivers: []
}
```
My notification method:
```
public function sendNotification()
{
    $notificationBuilder = new PayloadNotificationBuilder();
    $notificationBuilder->setTitle('Message from Admin')
        ->setBody(request('message'));

    $notification = $notificationBuilder->build();

    $token = "cljznXowYtU:APA91bE9WIveYdT9x8aeK56tPfd95cNwZdm30EzLsxoQT2i1oOKrvn54M2Fuz66PvOrBFJdQr1CQY69K4tt8waz5JY01RfbNkd-8W1RAROr9pM-ps_XD47g9Fqmg7YO91QVkg46qvX80";

    $downstreamResponse = FCM::sendTo($token, null, $notification, null);
}
```
What could I be doing wrong?

**Comment by brozot** [comment]
Hi, 

I think that the issue is coming from there :   ```return $this->app[ 'config' ][ 'fcm.driver' ];```

Are you sure that your fcm.php config file is correct ?

```
return [
    'driver' => env('FCM_PROTOCOL', 'http'),
    'log_enabled' => false,

    'http' => [
        'server_key' => env('FCM_SERVER_KEY', 'Your FCM server key'),
        'sender_id' => env('FCM_SENDER_ID', 'Your sender id'),
        'server_send_url' => 'https://fcm.googleapis.com/fcm/send',
        'server_group_url' => 'https://android.googleapis.com/gcm/notification',
        'timeout' => 30.0, // in second
    ],
];
```

**Comment by MJegorovas** [comment]
Hello, thanks for the reply.

Yes fcm.php file is completely same. What I found is that when look at what is stored in `$this->app['config']` there is no value with name of fcm.http even though 'LaravelFCM' is listed in service providers. What could be the problem of this? Maybe I'm missing some kind of step in installation?

**Comment by brozot** [comment]
weird, 
Which version of Laravel your project is using ?

**Comment by MJegorovas** [comment]
Laravel Framework 6.5.2

**Comment by brozot** [comment]
could you try to remove the directory `vendor/brozot` and run composer install again ?

**Comment by MJegorovas** [comment]
Probably my laravel is somehow broken. Just tried to setup this in other project and everything worked. Still, have no idea what is causing this though, because reinstalling didn't help.

**Comment by JayGajjar** [comment]
for me this worked as we are changing .env file its necessary 

php artisan config:cache

**Comment by md-salehzadeh** [comment]
you must publish the config file

```
php artisan vendor:publish --provider="LaravelFCM\FCMServiceProvider"
```

and in lumen:

Copy the config file ```fcm.php``` manually from the directory ```/vendor/brozot/laravel-fcm/config``` to the directory ```/config``` (you may need to create this directory).
